# Environment variables for Tatvacare HealthtechCRM (use in Vercel Project Settings → Environment Variables)
# Values below are placeholders. Replace as appropriate for each environment.
defaults:
  NEXT_PUBLIC_API_BASE_URL: "https://api.your-domain.com"
  NEXTAUTH_URL: "https://crm.your-domain.com"
  NEXTAUTH_SECRET: "<generate-strong-random>"
  AUTH0_DOMAIN: "your-tenant.auth0.com"
  AUTH0_CLIENT_ID: ""
  AUTH0_CLIENT_SECRET: ""
  AUTH0_ISSUER_BASE_URL: "https://your-tenant.auth0.com"
  NEXT_PUBLIC_OPENID_AUDIENCE: "https://api.your-domain.com"
  NEXT_PUBLIC_FEATURE_CALENDAR: "true"
  NEXT_PUBLIC_FEATURE_ESIGN: "true"
  NEXT_PUBLIC_FEATURE_RAZORPAY: "false"

# Notes:
# - Keys that start with NEXT_PUBLIC_ are exposed to the browser. Do NOT put secrets there.
# - Set these in Vercel → Project → Settings → Environment Variables for Production, Preview, and Development.
# - For local dev (Next.js), you can copy these into a .env.local file (not committed).
